name: daily_quotes
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  auto_route: ^9.2.2
  auto_route_generator: ^9.0.0
  flutter_bloc: ^8.1.6
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0
  build_runner: ^2.4.13
  url_launcher: ^6.3.1
  animated_background: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

